// source: any_joint_command.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.reachy.sdk.joint.AnyJointsCommand');
goog.provide('proto.reachy.sdk.joint.AnyJointsCommand.CommandCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Timestamp');
goog.require('proto.reachy.sdk.joint.JointsCommand');
goog.require('proto.reachy.sdk.kinematics.FullBodyCartesianCommand');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reachy.sdk.joint.AnyJointsCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.reachy.sdk.joint.AnyJointsCommand.oneofGroups_);
};
goog.inherits(proto.reachy.sdk.joint.AnyJointsCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reachy.sdk.joint.AnyJointsCommand.displayName = 'proto.reachy.sdk.joint.AnyJointsCommand';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.reachy.sdk.joint.AnyJointsCommand.oneofGroups_ = [[1,3]];

/**
 * @enum {number}
 */
proto.reachy.sdk.joint.AnyJointsCommand.CommandCase = {
  COMMAND_NOT_SET: 0,
  FULL_BODY: 1,
  JOINTS: 3
};

/**
 * @return {proto.reachy.sdk.joint.AnyJointsCommand.CommandCase}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.getCommandCase = function() {
  return /** @type {proto.reachy.sdk.joint.AnyJointsCommand.CommandCase} */(jspb.Message.computeOneofCase(this, proto.reachy.sdk.joint.AnyJointsCommand.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.reachy.sdk.joint.AnyJointsCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reachy.sdk.joint.AnyJointsCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.AnyJointsCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    fullBody: (f = msg.getFullBody()) && proto.reachy.sdk.kinematics.FullBodyCartesianCommand.toObject(includeInstance, f),
    joints: (f = msg.getJoints()) && proto.reachy.sdk.joint.JointsCommand.toObject(includeInstance, f),
    timestamp: (f = msg.getTimestamp()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand}
 */
proto.reachy.sdk.joint.AnyJointsCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reachy.sdk.joint.AnyJointsCommand;
  return proto.reachy.sdk.joint.AnyJointsCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reachy.sdk.joint.AnyJointsCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand}
 */
proto.reachy.sdk.joint.AnyJointsCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.reachy.sdk.kinematics.FullBodyCartesianCommand;
      reader.readMessage(value,proto.reachy.sdk.kinematics.FullBodyCartesianCommand.deserializeBinaryFromReader);
      msg.setFullBody(value);
      break;
    case 3:
      var value = new proto.reachy.sdk.joint.JointsCommand;
      reader.readMessage(value,proto.reachy.sdk.joint.JointsCommand.deserializeBinaryFromReader);
      msg.setJoints(value);
      break;
    case 15:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reachy.sdk.joint.AnyJointsCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reachy.sdk.joint.AnyJointsCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.AnyJointsCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFullBody();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.reachy.sdk.kinematics.FullBodyCartesianCommand.serializeBinaryToWriter
    );
  }
  f = message.getJoints();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.reachy.sdk.joint.JointsCommand.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional reachy.sdk.kinematics.FullBodyCartesianCommand full_body = 1;
 * @return {?proto.reachy.sdk.kinematics.FullBodyCartesianCommand}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.getFullBody = function() {
  return /** @type{?proto.reachy.sdk.kinematics.FullBodyCartesianCommand} */ (
    jspb.Message.getWrapperField(this, proto.reachy.sdk.kinematics.FullBodyCartesianCommand, 1));
};


/**
 * @param {?proto.reachy.sdk.kinematics.FullBodyCartesianCommand|undefined} value
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand} returns this
*/
proto.reachy.sdk.joint.AnyJointsCommand.prototype.setFullBody = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.reachy.sdk.joint.AnyJointsCommand.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand} returns this
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.clearFullBody = function() {
  return this.setFullBody(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.hasFullBody = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional JointsCommand joints = 3;
 * @return {?proto.reachy.sdk.joint.JointsCommand}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.getJoints = function() {
  return /** @type{?proto.reachy.sdk.joint.JointsCommand} */ (
    jspb.Message.getWrapperField(this, proto.reachy.sdk.joint.JointsCommand, 3));
};


/**
 * @param {?proto.reachy.sdk.joint.JointsCommand|undefined} value
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand} returns this
*/
proto.reachy.sdk.joint.AnyJointsCommand.prototype.setJoints = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.reachy.sdk.joint.AnyJointsCommand.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand} returns this
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.clearJoints = function() {
  return this.setJoints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.hasJoints = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp timestamp = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand} returns this
*/
proto.reachy.sdk.joint.AnyJointsCommand.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.AnyJointsCommand} returns this
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.AnyJointsCommand.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 15) != null;
};


