// source: config.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.reachy.sdk.config.ConfigReachy');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reachy.sdk.config.ConfigReachy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reachy.sdk.config.ConfigReachy.repeatedFields_, null);
};
goog.inherits(proto.reachy.sdk.config.ConfigReachy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reachy.sdk.config.ConfigReachy.displayName = 'proto.reachy.sdk.config.ConfigReachy';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reachy.sdk.config.ConfigReachy.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reachy.sdk.config.ConfigReachy.prototype.toObject = function(opt_includeInstance) {
  return proto.reachy.sdk.config.ConfigReachy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reachy.sdk.config.ConfigReachy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.config.ConfigReachy.toObject = function(includeInstance, msg) {
  var f, obj = {
    generation: jspb.Message.getFieldWithDefault(msg, 1, 0),
    mobileBasePresence: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    cameraParametersList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    config: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reachy.sdk.config.ConfigReachy}
 */
proto.reachy.sdk.config.ConfigReachy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reachy.sdk.config.ConfigReachy;
  return proto.reachy.sdk.config.ConfigReachy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reachy.sdk.config.ConfigReachy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reachy.sdk.config.ConfigReachy}
 */
proto.reachy.sdk.config.ConfigReachy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGeneration(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMobileBasePresence(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setCameraParametersList(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reachy.sdk.config.ConfigReachy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reachy.sdk.config.ConfigReachy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reachy.sdk.config.ConfigReachy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.config.ConfigReachy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGeneration();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getMobileBasePresence();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCameraParametersList();
  if (f.length > 0) {
    writer.writePackedFloat(
      3,
      f
    );
  }
  f = message.getConfig();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint32 generation = 1;
 * @return {number}
 */
proto.reachy.sdk.config.ConfigReachy.prototype.getGeneration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.reachy.sdk.config.ConfigReachy} returns this
 */
proto.reachy.sdk.config.ConfigReachy.prototype.setGeneration = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool mobile_base_presence = 2;
 * @return {boolean}
 */
proto.reachy.sdk.config.ConfigReachy.prototype.getMobileBasePresence = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.reachy.sdk.config.ConfigReachy} returns this
 */
proto.reachy.sdk.config.ConfigReachy.prototype.setMobileBasePresence = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * repeated float camera_parameters = 3;
 * @return {!Array<number>}
 */
proto.reachy.sdk.config.ConfigReachy.prototype.getCameraParametersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.reachy.sdk.config.ConfigReachy} returns this
 */
proto.reachy.sdk.config.ConfigReachy.prototype.setCameraParametersList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.reachy.sdk.config.ConfigReachy} returns this
 */
proto.reachy.sdk.config.ConfigReachy.prototype.addCameraParameters = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reachy.sdk.config.ConfigReachy} returns this
 */
proto.reachy.sdk.config.ConfigReachy.prototype.clearCameraParametersList = function() {
  return this.setCameraParametersList([]);
};


/**
 * optional string config = 4;
 * @return {string}
 */
proto.reachy.sdk.config.ConfigReachy.prototype.getConfig = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.reachy.sdk.config.ConfigReachy} returns this
 */
proto.reachy.sdk.config.ConfigReachy.prototype.setConfig = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


