// source: joint.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.reachy.sdk.joint.JointState');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.BoolValue');
goog.require('proto.google.protobuf.FloatValue');
goog.require('proto.google.protobuf.UInt32Value');
goog.require('proto.reachy.sdk.joint.PIDValue');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reachy.sdk.joint.JointState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.reachy.sdk.joint.JointState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reachy.sdk.joint.JointState.displayName = 'proto.reachy.sdk.joint.JointState';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reachy.sdk.joint.JointState.prototype.toObject = function(opt_includeInstance) {
  return proto.reachy.sdk.joint.JointState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reachy.sdk.joint.JointState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.JointState.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uid: (f = msg.getUid()) && proto.google.protobuf.UInt32Value.toObject(includeInstance, f),
    presentPosition: (f = msg.getPresentPosition()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    presentSpeed: (f = msg.getPresentSpeed()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    presentLoad: (f = msg.getPresentLoad()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    temperature: (f = msg.getTemperature()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    compliant: (f = msg.getCompliant()) && proto.google.protobuf.BoolValue.toObject(includeInstance, f),
    goalPosition: (f = msg.getGoalPosition()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    speedLimit: (f = msg.getSpeedLimit()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    torqueLimit: (f = msg.getTorqueLimit()) && proto.google.protobuf.FloatValue.toObject(includeInstance, f),
    pid: (f = msg.getPid()) && proto.reachy.sdk.joint.PIDValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reachy.sdk.joint.JointState}
 */
proto.reachy.sdk.joint.JointState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reachy.sdk.joint.JointState;
  return proto.reachy.sdk.joint.JointState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reachy.sdk.joint.JointState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reachy.sdk.joint.JointState}
 */
proto.reachy.sdk.joint.JointState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.google.protobuf.UInt32Value;
      reader.readMessage(value,proto.google.protobuf.UInt32Value.deserializeBinaryFromReader);
      msg.setUid(value);
      break;
    case 3:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setPresentPosition(value);
      break;
    case 4:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setPresentSpeed(value);
      break;
    case 5:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setPresentLoad(value);
      break;
    case 6:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setTemperature(value);
      break;
    case 7:
      var value = new proto.google.protobuf.BoolValue;
      reader.readMessage(value,proto.google.protobuf.BoolValue.deserializeBinaryFromReader);
      msg.setCompliant(value);
      break;
    case 8:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setGoalPosition(value);
      break;
    case 9:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setSpeedLimit(value);
      break;
    case 10:
      var value = new proto.google.protobuf.FloatValue;
      reader.readMessage(value,proto.google.protobuf.FloatValue.deserializeBinaryFromReader);
      msg.setTorqueLimit(value);
      break;
    case 11:
      var value = new proto.reachy.sdk.joint.PIDValue;
      reader.readMessage(value,proto.reachy.sdk.joint.PIDValue.deserializeBinaryFromReader);
      msg.setPid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reachy.sdk.joint.JointState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reachy.sdk.joint.JointState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reachy.sdk.joint.JointState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.JointState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.UInt32Value.serializeBinaryToWriter
    );
  }
  f = message.getPresentPosition();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getPresentSpeed();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getPresentLoad();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getTemperature();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getCompliant();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.google.protobuf.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getGoalPosition();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getSpeedLimit();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getTorqueLimit();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.google.protobuf.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getPid();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.reachy.sdk.joint.PIDValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.reachy.sdk.joint.JointState.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.UInt32Value uid = 2;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.reachy.sdk.joint.JointState.prototype.getUid = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.UInt32Value, 2));
};


/**
 * @param {?proto.google.protobuf.UInt32Value|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setUid = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearUid = function() {
  return this.setUid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasUid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.FloatValue present_position = 3;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getPresentPosition = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 3));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setPresentPosition = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearPresentPosition = function() {
  return this.setPresentPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasPresentPosition = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.FloatValue present_speed = 4;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getPresentSpeed = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 4));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setPresentSpeed = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearPresentSpeed = function() {
  return this.setPresentSpeed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasPresentSpeed = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.FloatValue present_load = 5;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getPresentLoad = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 5));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setPresentLoad = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearPresentLoad = function() {
  return this.setPresentLoad(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasPresentLoad = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.FloatValue temperature = 6;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getTemperature = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 6));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setTemperature = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearTemperature = function() {
  return this.setTemperature(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasTemperature = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.BoolValue compliant = 7;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getCompliant = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.BoolValue, 7));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setCompliant = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearCompliant = function() {
  return this.setCompliant(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasCompliant = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.FloatValue goal_position = 8;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getGoalPosition = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 8));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setGoalPosition = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearGoalPosition = function() {
  return this.setGoalPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasGoalPosition = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.FloatValue speed_limit = 9;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getSpeedLimit = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 9));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setSpeedLimit = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearSpeedLimit = function() {
  return this.setSpeedLimit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasSpeedLimit = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.FloatValue torque_limit = 10;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getTorqueLimit = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.FloatValue, 10));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setTorqueLimit = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearTorqueLimit = function() {
  return this.setTorqueLimit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasTorqueLimit = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional PIDValue pid = 11;
 * @return {?proto.reachy.sdk.joint.PIDValue}
 */
proto.reachy.sdk.joint.JointState.prototype.getPid = function() {
  return /** @type{?proto.reachy.sdk.joint.PIDValue} */ (
    jspb.Message.getWrapperField(this, proto.reachy.sdk.joint.PIDValue, 11));
};


/**
 * @param {?proto.reachy.sdk.joint.PIDValue|undefined} value
 * @return {!proto.reachy.sdk.joint.JointState} returns this
*/
proto.reachy.sdk.joint.JointState.prototype.setPid = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.JointState} returns this
 */
proto.reachy.sdk.joint.JointState.prototype.clearPid = function() {
  return this.setPid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.JointState.prototype.hasPid = function() {
  return jspb.Message.getField(this, 11) != null;
};


