// source: joint.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.reachy.sdk.joint.PIDValue');
goog.provide('proto.reachy.sdk.joint.PIDValue.GainsCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.reachy.sdk.joint.ComplianceMarginSlope');
goog.require('proto.reachy.sdk.joint.PIDGains');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reachy.sdk.joint.PIDValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.reachy.sdk.joint.PIDValue.oneofGroups_);
};
goog.inherits(proto.reachy.sdk.joint.PIDValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reachy.sdk.joint.PIDValue.displayName = 'proto.reachy.sdk.joint.PIDValue';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.reachy.sdk.joint.PIDValue.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.reachy.sdk.joint.PIDValue.GainsCase = {
  GAINS_NOT_SET: 0,
  PID: 1,
  COMPLIANCE: 2
};

/**
 * @return {proto.reachy.sdk.joint.PIDValue.GainsCase}
 */
proto.reachy.sdk.joint.PIDValue.prototype.getGainsCase = function() {
  return /** @type {proto.reachy.sdk.joint.PIDValue.GainsCase} */(jspb.Message.computeOneofCase(this, proto.reachy.sdk.joint.PIDValue.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reachy.sdk.joint.PIDValue.prototype.toObject = function(opt_includeInstance) {
  return proto.reachy.sdk.joint.PIDValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reachy.sdk.joint.PIDValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.PIDValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    pid: (f = msg.getPid()) && proto.reachy.sdk.joint.PIDGains.toObject(includeInstance, f),
    compliance: (f = msg.getCompliance()) && proto.reachy.sdk.joint.ComplianceMarginSlope.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reachy.sdk.joint.PIDValue}
 */
proto.reachy.sdk.joint.PIDValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reachy.sdk.joint.PIDValue;
  return proto.reachy.sdk.joint.PIDValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reachy.sdk.joint.PIDValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reachy.sdk.joint.PIDValue}
 */
proto.reachy.sdk.joint.PIDValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.reachy.sdk.joint.PIDGains;
      reader.readMessage(value,proto.reachy.sdk.joint.PIDGains.deserializeBinaryFromReader);
      msg.setPid(value);
      break;
    case 2:
      var value = new proto.reachy.sdk.joint.ComplianceMarginSlope;
      reader.readMessage(value,proto.reachy.sdk.joint.ComplianceMarginSlope.deserializeBinaryFromReader);
      msg.setCompliance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reachy.sdk.joint.PIDValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reachy.sdk.joint.PIDValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reachy.sdk.joint.PIDValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.PIDValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.reachy.sdk.joint.PIDGains.serializeBinaryToWriter
    );
  }
  f = message.getCompliance();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.reachy.sdk.joint.ComplianceMarginSlope.serializeBinaryToWriter
    );
  }
};


/**
 * optional PIDGains pid = 1;
 * @return {?proto.reachy.sdk.joint.PIDGains}
 */
proto.reachy.sdk.joint.PIDValue.prototype.getPid = function() {
  return /** @type{?proto.reachy.sdk.joint.PIDGains} */ (
    jspb.Message.getWrapperField(this, proto.reachy.sdk.joint.PIDGains, 1));
};


/**
 * @param {?proto.reachy.sdk.joint.PIDGains|undefined} value
 * @return {!proto.reachy.sdk.joint.PIDValue} returns this
*/
proto.reachy.sdk.joint.PIDValue.prototype.setPid = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.reachy.sdk.joint.PIDValue.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.PIDValue} returns this
 */
proto.reachy.sdk.joint.PIDValue.prototype.clearPid = function() {
  return this.setPid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.PIDValue.prototype.hasPid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ComplianceMarginSlope compliance = 2;
 * @return {?proto.reachy.sdk.joint.ComplianceMarginSlope}
 */
proto.reachy.sdk.joint.PIDValue.prototype.getCompliance = function() {
  return /** @type{?proto.reachy.sdk.joint.ComplianceMarginSlope} */ (
    jspb.Message.getWrapperField(this, proto.reachy.sdk.joint.ComplianceMarginSlope, 2));
};


/**
 * @param {?proto.reachy.sdk.joint.ComplianceMarginSlope|undefined} value
 * @return {!proto.reachy.sdk.joint.PIDValue} returns this
*/
proto.reachy.sdk.joint.PIDValue.prototype.setCompliance = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.reachy.sdk.joint.PIDValue.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.PIDValue} returns this
 */
proto.reachy.sdk.joint.PIDValue.prototype.clearCompliance = function() {
  return this.setCompliance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.PIDValue.prototype.hasCompliance = function() {
  return jspb.Message.getField(this, 2) != null;
};


