// source: sensor.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.reachy.sdk.joint.SensorState');
goog.provide('proto.reachy.sdk.joint.SensorState.StateCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.reachy.sdk.joint.ForceSensorState');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reachy.sdk.joint.SensorState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.reachy.sdk.joint.SensorState.oneofGroups_);
};
goog.inherits(proto.reachy.sdk.joint.SensorState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reachy.sdk.joint.SensorState.displayName = 'proto.reachy.sdk.joint.SensorState';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.reachy.sdk.joint.SensorState.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.reachy.sdk.joint.SensorState.StateCase = {
  STATE_NOT_SET: 0,
  FORCE_SENSOR_STATE: 1
};

/**
 * @return {proto.reachy.sdk.joint.SensorState.StateCase}
 */
proto.reachy.sdk.joint.SensorState.prototype.getStateCase = function() {
  return /** @type {proto.reachy.sdk.joint.SensorState.StateCase} */(jspb.Message.computeOneofCase(this, proto.reachy.sdk.joint.SensorState.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reachy.sdk.joint.SensorState.prototype.toObject = function(opt_includeInstance) {
  return proto.reachy.sdk.joint.SensorState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reachy.sdk.joint.SensorState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.SensorState.toObject = function(includeInstance, msg) {
  var f, obj = {
    forceSensorState: (f = msg.getForceSensorState()) && proto.reachy.sdk.joint.ForceSensorState.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reachy.sdk.joint.SensorState}
 */
proto.reachy.sdk.joint.SensorState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reachy.sdk.joint.SensorState;
  return proto.reachy.sdk.joint.SensorState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reachy.sdk.joint.SensorState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reachy.sdk.joint.SensorState}
 */
proto.reachy.sdk.joint.SensorState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.reachy.sdk.joint.ForceSensorState;
      reader.readMessage(value,proto.reachy.sdk.joint.ForceSensorState.deserializeBinaryFromReader);
      msg.setForceSensorState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reachy.sdk.joint.SensorState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reachy.sdk.joint.SensorState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reachy.sdk.joint.SensorState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reachy.sdk.joint.SensorState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getForceSensorState();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.reachy.sdk.joint.ForceSensorState.serializeBinaryToWriter
    );
  }
};


/**
 * optional ForceSensorState force_sensor_state = 1;
 * @return {?proto.reachy.sdk.joint.ForceSensorState}
 */
proto.reachy.sdk.joint.SensorState.prototype.getForceSensorState = function() {
  return /** @type{?proto.reachy.sdk.joint.ForceSensorState} */ (
    jspb.Message.getWrapperField(this, proto.reachy.sdk.joint.ForceSensorState, 1));
};


/**
 * @param {?proto.reachy.sdk.joint.ForceSensorState|undefined} value
 * @return {!proto.reachy.sdk.joint.SensorState} returns this
*/
proto.reachy.sdk.joint.SensorState.prototype.setForceSensorState = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.reachy.sdk.joint.SensorState.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.reachy.sdk.joint.SensorState} returns this
 */
proto.reachy.sdk.joint.SensorState.prototype.clearForceSensorState = function() {
  return this.setForceSensorState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.reachy.sdk.joint.SensorState.prototype.hasForceSensorState = function() {
  return jspb.Message.getField(this, 1) != null;
};


