# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x11reachy.sdk.config\x1a\x1bgoogle/protobuf/empty.proto\"@\n\x0c\x43onfigReachy\x12\x12\n\ngeneration\x18\x01 \x01(\r\x12\x1c\n\x14mobile_base_presence\x18\x02 \x01(\x08\x32[\n\rConfigService\x12J\n\x0fGetReachyConfig\x12\x16.google.protobuf.Empty\x1a\x1f.reachy.sdk.config.ConfigReachyb\x06proto3')



_CONFIGREACHY = DESCRIPTOR.message_types_by_name['ConfigReachy']
ConfigReachy = _reflection.GeneratedProtocolMessageType('ConfigReachy', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGREACHY,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.config.ConfigReachy)
  })
_sym_db.RegisterMessage(ConfigReachy)

_CONFIGSERVICE = DESCRIPTOR.services_by_name['ConfigService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIGREACHY._serialized_start=64
  _CONFIGREACHY._serialized_end=128
  _CONFIGSERVICE._serialized_start=130
  _CONFIGSERVICE._serialized_end=221
# @@protoc_insertion_point(module_scope)
