# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import joint_command_pb2 as joint__command__pb2


class JointCommandServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendCommand = channel.unary_unary(
        '/reachy.sdk.joint.JointCommandService/SendCommand',
        request_serializer=joint__command__pb2.JointCommand.SerializeToString,
        response_deserializer=joint__command__pb2.JointCommandAck.FromString,
        )
    self.SendAllJointsCommand = channel.unary_unary(
        '/reachy.sdk.joint.JointCommandService/SendAllJointsCommand',
        request_serializer=joint__command__pb2.MultipleJointsCommand.SerializeToString,
        response_deserializer=joint__command__pb2.JointCommandAck.FromString,
        )
    self.StreamJointsCommand = channel.stream_unary(
        '/reachy.sdk.joint.JointCommandService/StreamJointsCommand',
        request_serializer=joint__command__pb2.MultipleJointsCommand.SerializeToString,
        response_deserializer=joint__command__pb2.JointCommandAck.FromString,
        )


class JointCommandServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendAllJointsCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamJointsCommand(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JointCommandServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendCommand,
          request_deserializer=joint__command__pb2.JointCommand.FromString,
          response_serializer=joint__command__pb2.JointCommandAck.SerializeToString,
      ),
      'SendAllJointsCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendAllJointsCommand,
          request_deserializer=joint__command__pb2.MultipleJointsCommand.FromString,
          response_serializer=joint__command__pb2.JointCommandAck.SerializeToString,
      ),
      'StreamJointsCommand': grpc.stream_unary_rpc_method_handler(
          servicer.StreamJointsCommand,
          request_deserializer=joint__command__pb2.MultipleJointsCommand.FromString,
          response_serializer=joint__command__pb2.JointCommandAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'reachy.sdk.joint.JointCommandService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
