# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kinematics_pb2 as kinematics__pb2
import metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x0freachy.sdk.pose\x1a\x10kinematics.proto\x1a\x0emetadata.proto\"Y\n\tTolerance\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\r\n\x05rot_x\x18\x04 \x01(\x01\x12\r\n\x05rot_y\x18\x05 \x01(\x01\x12\r\n\x05rot_z\x18\x06 \x01(\x01\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"h\n\x04Pose\x12(\n\x08position\x18\x01 \x01(\x0b\x32\x16.reachy.sdk.pose.Point\x12\x36\n\x0borientation\x18\x02 \x01(\x0b\x32!.reachy.sdk.kinematics.Quaternion\"-\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\"_\n\x0bPoseStamped\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.reachy.sdk.metadata.Header\x12#\n\x04pose\x18\x02 \x01(\x0b\x32\x15.reachy.sdk.pose.Poseb\x06proto3')



_TOLERANCE = DESCRIPTOR.message_types_by_name['Tolerance']
_POINT = DESCRIPTOR.message_types_by_name['Point']
_VECTOR3 = DESCRIPTOR.message_types_by_name['Vector3']
_POSE = DESCRIPTOR.message_types_by_name['Pose']
_POSE2D = DESCRIPTOR.message_types_by_name['Pose2D']
_POSESTAMPED = DESCRIPTOR.message_types_by_name['PoseStamped']
Tolerance = _reflection.GeneratedProtocolMessageType('Tolerance', (_message.Message,), {
  'DESCRIPTOR' : _TOLERANCE,
  '__module__' : 'pose_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.pose.Tolerance)
  })
_sym_db.RegisterMessage(Tolerance)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'pose_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.pose.Point)
  })
_sym_db.RegisterMessage(Point)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3,
  '__module__' : 'pose_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.pose.Vector3)
  })
_sym_db.RegisterMessage(Vector3)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'pose_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.pose.Pose)
  })
_sym_db.RegisterMessage(Pose)

Pose2D = _reflection.GeneratedProtocolMessageType('Pose2D', (_message.Message,), {
  'DESCRIPTOR' : _POSE2D,
  '__module__' : 'pose_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.pose.Pose2D)
  })
_sym_db.RegisterMessage(Pose2D)

PoseStamped = _reflection.GeneratedProtocolMessageType('PoseStamped', (_message.Message,), {
  'DESCRIPTOR' : _POSESTAMPED,
  '__module__' : 'pose_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.pose.PoseStamped)
  })
_sym_db.RegisterMessage(PoseStamped)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOLERANCE._serialized_start=65
  _TOLERANCE._serialized_end=154
  _POINT._serialized_start=156
  _POINT._serialized_end=196
  _VECTOR3._serialized_start=198
  _VECTOR3._serialized_end=240
  _POSE._serialized_start=242
  _POSE._serialized_end=346
  _POSE2D._serialized_start=348
  _POSE2D._serialized_end=393
  _POSESTAMPED._serialized_start=395
  _POSESTAMPED._serialized_end=490
# @@protoc_insertion_point(module_scope)
