# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import restart_signal_pb2 as restart__signal__pb2


class RestartServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRestartSignal = channel.unary_unary(
                '/reachy.sdk.restart.RestartService/SendRestartSignal',
                request_serializer=restart__signal__pb2.RestartCmd.SerializeToString,
                response_deserializer=restart__signal__pb2.RestartSignalAck.FromString,
                )


class RestartServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRestartSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRestartSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRestartSignal,
                    request_deserializer=restart__signal__pb2.RestartCmd.FromString,
                    response_serializer=restart__signal__pb2.RestartSignalAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reachy.sdk.restart.RestartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RestartService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRestartSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reachy.sdk.restart.RestartService/SendRestartSignal',
            restart__signal__pb2.RestartCmd.SerializeToString,
            restart__signal__pb2.RestartSignalAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
