# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import teleop_pb2 as teleop__pb2


class TeleoperationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FollowMovement = channel.unary_unary(
        '/reachy.teleop.TeleoperationService/FollowMovement',
        request_serializer=teleop__pb2.EndEffector.SerializeToString,
        response_deserializer=teleop__pb2.JointCommandAck.FromString,
        )


class TeleoperationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FollowMovement(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TeleoperationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FollowMovement': grpc.unary_unary_rpc_method_handler(
          servicer.FollowMovement,
          request_deserializer=teleop__pb2.EndEffector.FromString,
          response_serializer=teleop__pb2.JointCommandAck.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'reachy.teleop.TeleoperationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
