// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: automatic_grasping.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Sdk.Grasping {
  public static partial class AutomaticGraspingCommandService
  {
    static readonly string __ServiceName = "reachy.sdk.grasping.AutomaticGraspingCommandService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Reachy.Sdk.Grasping.AutomaticGraspingCommand> __Marshaller_reachy_sdk_grasping_AutomaticGraspingCommand = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Grasping.AutomaticGraspingCommand.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck> __Marshaller_reachy_sdk_grasping_AutomaticGraspingCommandAck = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck.Parser));

    static readonly grpc::Method<global::Reachy.Sdk.Grasping.AutomaticGraspingCommand, global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck> __Method_RequestAutomaticGraspingCommand = new grpc::Method<global::Reachy.Sdk.Grasping.AutomaticGraspingCommand, global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RequestAutomaticGraspingCommand",
        __Marshaller_reachy_sdk_grasping_AutomaticGraspingCommand,
        __Marshaller_reachy_sdk_grasping_AutomaticGraspingCommandAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Sdk.Grasping.AutomaticGraspingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AutomaticGraspingCommandService</summary>
    [grpc::BindServiceMethod(typeof(AutomaticGraspingCommandService), "BindService")]
    public abstract partial class AutomaticGraspingCommandServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck> RequestAutomaticGraspingCommand(global::Reachy.Sdk.Grasping.AutomaticGraspingCommand request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AutomaticGraspingCommandService</summary>
    public partial class AutomaticGraspingCommandServiceClient : grpc::ClientBase<AutomaticGraspingCommandServiceClient>
    {
      /// <summary>Creates a new client for AutomaticGraspingCommandService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AutomaticGraspingCommandServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AutomaticGraspingCommandService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AutomaticGraspingCommandServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AutomaticGraspingCommandServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AutomaticGraspingCommandServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck RequestAutomaticGraspingCommand(global::Reachy.Sdk.Grasping.AutomaticGraspingCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestAutomaticGraspingCommand(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck RequestAutomaticGraspingCommand(global::Reachy.Sdk.Grasping.AutomaticGraspingCommand request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RequestAutomaticGraspingCommand, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck> RequestAutomaticGraspingCommandAsync(global::Reachy.Sdk.Grasping.AutomaticGraspingCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestAutomaticGraspingCommandAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck> RequestAutomaticGraspingCommandAsync(global::Reachy.Sdk.Grasping.AutomaticGraspingCommand request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RequestAutomaticGraspingCommand, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AutomaticGraspingCommandServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AutomaticGraspingCommandServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AutomaticGraspingCommandServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RequestAutomaticGraspingCommand, serviceImpl.RequestAutomaticGraspingCommand).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AutomaticGraspingCommandServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RequestAutomaticGraspingCommand, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Grasping.AutomaticGraspingCommand, global::Reachy.Sdk.Grasping.AutomaticGraspingCommandAck>(serviceImpl.RequestAutomaticGraspingCommand));
    }

  }
}
#endregion
