# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: load_sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='load_sensor.proto',
  package='reachy.sdk.joint',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11load_sensor.proto\x12\x10reachy.sdk.joint\"\x19\n\tLoadValue\x12\x0c\n\x04load\x18\x01 \x01(\x02\"\x14\n\x04Side\x12\x0c\n\x04side\x18\x01 \x01(\t2M\n\x0bLoadService\x12>\n\x07GetLoad\x12\x16.reachy.sdk.joint.Side\x1a\x1b.reachy.sdk.joint.LoadValueb\x06proto3'
)




_LOADVALUE = _descriptor.Descriptor(
  name='LoadValue',
  full_name='reachy.sdk.joint.LoadValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='load', full_name='reachy.sdk.joint.LoadValue.load', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=64,
)


_SIDE = _descriptor.Descriptor(
  name='Side',
  full_name='reachy.sdk.joint.Side',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='reachy.sdk.joint.Side.side', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['LoadValue'] = _LOADVALUE
DESCRIPTOR.message_types_by_name['Side'] = _SIDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadValue = _reflection.GeneratedProtocolMessageType('LoadValue', (_message.Message,), {
  'DESCRIPTOR' : _LOADVALUE,
  '__module__' : 'load_sensor_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.joint.LoadValue)
  })
_sym_db.RegisterMessage(LoadValue)

Side = _reflection.GeneratedProtocolMessageType('Side', (_message.Message,), {
  'DESCRIPTOR' : _SIDE,
  '__module__' : 'load_sensor_pb2'
  # @@protoc_insertion_point(class_scope:reachy.sdk.joint.Side)
  })
_sym_db.RegisterMessage(Side)



_LOADSERVICE = _descriptor.ServiceDescriptor(
  name='LoadService',
  full_name='reachy.sdk.joint.LoadService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=88,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLoad',
    full_name='reachy.sdk.joint.LoadService.GetLoad',
    index=0,
    containing_service=None,
    input_type=_SIDE,
    output_type=_LOADVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADSERVICE)

DESCRIPTOR.services_by_name['LoadService'] = _LOADSERVICE

# @@protoc_insertion_point(module_scope)
